# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('website', models.URLField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('affiliation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk_app.Candidate')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.IntegerField(blank=True, null=True)),
                ('friend_mix', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('registered', models.CharField(max_length=20)),
                ('affiliation', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pundit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('website', models.URLField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('employer', models.CharField(max_length=30)),
                ('affiliation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30)),
                ('intensity', models.IntegerField()),
                ('wonk_level', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_level', models.IntegerField()),
                ('change_mind', models.BooleanField()),
                ('made_choice', models.BooleanField()),
                ('top_area', models.CharField(max_length=30)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk_app.DinnerParty')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twt_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.TextField()),
                ('text', models.TextField()),
                ('retweet_count', models.IntegerField(null=True)),
                ('favorite_count', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='pundit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk_app.Pundit'),
        ),
    ]
