# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='office',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Give your party a name'),
        ),
    ]
