# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0003_auto_20160722_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='intensity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='wonk_level',
            field=models.CharField(max_length=20),
        ),
    ]
