# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0004_auto_20160722_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=30)),
                ('party', models.CharField(max_length=5)),
                ('total', models.FloatField()),
                ('as_of', models.CharField(max_length=10)),
                ('cash_on_hand', models.FloatField()),
                ('candidate_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
    ]
