# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0006_auto_20160723_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usfinance',
            options={'ordering': ['-cash_on_hand']},
        ),
        migrations.AddField(
            model_name='tweet',
            name='popular',
            field=models.IntegerField(null=True),
        ),
    ]
