# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0007_auto_20160723_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='popular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
