# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0008_auto_20160725_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twt_id',
            field=models.BigIntegerField(),
        ),
    ]
