# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0010_auto_20160726_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='twt_username',
            field=models.CharField(default='BarackObama', max_length=20),
        ),
    ]
