# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk_app', '0012_auto_20160728_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='host',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
