# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0014_auto_20160728_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerparty',
            name='party_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='survey',
            name='discussion_intensity',
            field=models.CharField(choices=[('Deep', 'Deep'), ('Medium', 'Medium'), ('Shallow', 'Shallow')], default='Medium', max_length=40),
        ),
        migrations.AlterField(
            model_name='survey',
            name='top_topic',
            field=models.CharField(choices=[('Values', 'Values'), ('Policy', 'Policy'), ('Personal qualities', 'Personal qualities')], default='Policy', max_length=40),
        ),
    ]
