# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0015_auto_20160728_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='dinner',
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talk_app.Survey'),
        ),
    ]
