# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0016_auto_20160730_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerparty',
            name='video',
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pundit',
            name='video_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pundit',
            name='video_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pundit',
            name='video_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
