# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0017_auto_20160730_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerparty',
            name='survey',
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_five',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_four',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_one',
            field=models.CharField(choices=[('Deep', 'Deep'), ('Medium', 'Medium'), ('Shallow', 'Shallow')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_seven',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_six',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_three',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dinnerparty',
            name='question_two',
            field=models.CharField(choices=[('Values', 'Values'), ('Policy', 'Policy'), ('Personal qualities', 'Personal qualities')], max_length=60, null=True),
        ),
    ]
