# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0018_auto_20160730_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='pundit',
            name='twt_username',
            field=models.CharField(default='BarackObama', max_length=20),
        ),
    ]
