# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0019_pundit_twt_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='host',
        ),
        migrations.RemoveField(
            model_name='video',
            name='host',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
