# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0021_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registered',
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_to_vote',
            field=models.CharField(choices=[('I am currently registered to vote', 'I am currently registered to vote'), ('I have never been registered', 'I have never been registered'), ('I was registered but am not now', 'I was registered but am not now')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_five',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_four',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_seven',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_six',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_three',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
