# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0023_auto_20160803_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerparty',
            name='friend_names',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_five',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_four',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_seven',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_six',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerparty',
            name='question_three',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
